# Proyecto Análisis Computacional de Datos: catálogo de plazaVea

**Curso:** Análisis Computacional de Datos (DS3021)
**Docente:** José Espinoza Melgarejo

**Integrantes:**
- Denilson Jermai Cuadros Villegas 202510232
- Enrique Eusebio Torres Chafloque 202510601
- Leo Alexander Torres Ccencho 202410078
- Valeria Bazán Meléndez 202410443
- Lucas Armando Aliaga Mena 201810550

**Fuente:** https://www.plazavea.com.pe/
**Técnica:** Selenium (renderizado) + BeautifulSoup (parseo del DOM)
**Repositorio:** [Proyecto-ACD](https://github.com/DnCuadros23/web-scraping-ACD.git)

---

## Contexto 

PlazaVea es una de las cadenas de supermercados más grandes del Perú y publica en su página web el catálogo completo de productos con los precios que están vigentes en ese momento. Esta información es útil porque permite construir, a partir de una fuente real y pública, un conjunto de datos sobre precios del mercado peruano: cuánto cuesta un producto, si tiene descuento, de qué marca es y en qué categoría se ubica.El problema de fondo es que esta información no está disponible en un formato fácil de analizar: está repartida en cientos de páginas web y cambia todos los días, así que nadie puede estudiarla a mano. Si se logra capturarla de forma ordenada, el impacto es concreto: permite comparar precios entre marcas, detectar qué categorías concentran más descuentos, y sirve como insumo real para practicar análisis de datos en vez de usar un dataset ya armado. Además, esta fuente no ofrece una API pública para descargar sus datos, así que obtenerla exige aplicar técnicas de web scraping, que es justamente lo que pide la actividad del curso.

### Objetivo

**Objetivo general:** Construir, mediante web scraping, un dataset con más de 1000 productos del catálogo de Pla-
zaVea, que incluya precio de venta, precio regular, descuento, marca y categoría de cada producto,
2
para tener una base de datos real y actualizada sobre precios de supermercado en el Perú.

**Objetivos específicos:**

- Extraer los datos del catálogo de PlazaVea usando Selenium y BeautifulSoup, respetando lo
que permite el archivo robots.txt y sin usar ninguna API interna del sitio.
- Limpiar y estandarizar la información extraída (precios como números, texto sin errores de
formato, sin duplicados) para que quede lista para análisis, manteniendo los valores nulos por
debajo del 10 % en cada columna.
- Documentar el dataset final con un diccionario de datos claro, y organizar todo el trabajo del
equipo en un informe que se entienda de principio a fin

**Política de nulos:** la rúbrica exige un máximo de 10% de nulos por columna en el dataset
preliminar. `precio_regular` y `descuento_pct` no son nulos reales cuando un producto no
tiene oferta activa (el precio regular es el mismo precio de venta y el descuento es 0), así
que se completan con ese valor en el extractor en vez de dejarlos como `NaN`. El precio con
tarjeta Oh! solo existe para una minoría de productos, así que se guarda como indicador
booleano (`tiene_precio_oh`) en vez de un precio numérico que sería mayormente nulo.

## Consideraciones éticas y técnicas

| Consideración | Cómo se cumple | Dónde |
|---|---|---|
| Respetar `robots.txt` | Se revisa antes de programar el scraper | Sección 2.1 |
| Ética y legalidad | Solo datos públicos de catálogo (precio, nombre, categoría); ningún dato personal | Sección 6 |
| Rendimiento | `time.sleep()` entre páginas y entre categorías | Secciones 8-9 |
| Headers | `User-Agent` realista (`UA`) en `requests` y en Selenium | Sección 1 y 3 |
| Manejo de errores | `try/except` con reintentos y espera creciente | Sección 8 |
| Almacenamiento incremental | CSV parcial por categoría antes de consolidar | Sección 9 |

## 1. Preparación del entorno

Estas son las tres librerías que vimos en clase para scraping. Aquí se usan dos:
Selenium para que el navegador ejecute el JavaScript del sitio, y BeautifulSoup para
parsear el HTML ya renderizado.

In [1]:
# Solo la primera vez. En local basta con: pip install -r requirements.txt
# !pip install selenium webdriver-manager beautifulsoup4 pandas lxml

In [2]:
import re, time, json
from collections import Counter
from datetime import datetime
from pathlib import Path
#Para extraer precios, para pausas entre peticiones, diccionario  
#Para encontrar repeticiones (para encontrar tarjetas de producto)
#Para poner fecha en cada fila y nombre del archivo
#Para manejo de rutas de archivos 
import requests
import pandas as pd
from bs4 import BeautifulSoup
#Hacer peticiones, Para convertir a diccionarios en un df,
#parsear html y navegar con selectores CSS


from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
#Maquinaria de Selenium, webdriver.chrome-abre-chrome, options para configurar esto
#Service-donde esta el ejecutable del chromerdriver, By-indica el tipo de selector
#WebDriverWail+excepted_conditions-esperas inteligentes, y no solo time.sleep(5) a ciegas
#Esperar por ejemplo hasta que un boton sea clikeable
#ChromeDriverManager-Descarga auto la version de chromedriver que coincide con chrome

BASE = "https://www.plazavea.com.pe"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")  # header realista

print("librerías cargadas")

#La url raiz y un user-agent de navegador "parece" una persona

librerías cargadas

## 2. Reconocimiento del sitio

Antes de escribir el scraper hay que responder dos preguntas: qué permite el sitio y
cómo entrega los datos. Todo lo que sigue justifica la técnica elegida.

### 2.1 robots.txt

Se revisa qué rutas declara el sitio como no rastreables. Esto define el alcance ético
y técnico de la extracción.

In [3]:
# robots.txt es un archivo de texto público, no un endpoint de datos
r = requests.get(f"{BASE}/robots.txt", headers={"User-Agent": UA}, timeout=20)
print("status:", r.status_code)
print(r.text[:1500])
#peticion http get, manda el header con el UA definido, si en 20 seg no responde
#se lanza una excepcion en vez de colgarse para siempre
#Los primeros 1500 caracteres del contenido-suficiente para ver que rutas
#declara el archivo como no permitidas


#robots.txt es un archivo publico de texto plano, igual que cualquier otra pag
#revisar antes de scrapear es escencial

status: 200
User-agent: *
Disallow: /checkout
Disallow: /sitemap/brand-1.xml
Disallow: /sitemap/brand-2.xml
Disallow: /sitemap/brand-3.xml

Sitemap: https://www.plazavea.com.pe/sitemap.xml

### 2.2 ¿El HTML estático trae los productos?

Prueba controlada: se descarga la categoría con `requests` (sin navegador) y se cuenta
cuántos precios aparecen en el HTML crudo. Si el número es cero, el catálogo se arma
con JavaScript en el navegador y `requests` + BeautifulSoup por sí solos no alcanzan.

In [4]:
url_prueba = f"{BASE}/abarrotes"


r = requests.get(url_prueba, headers={"User-Agent": UA}, timeout=30)
sopa_estatica = BeautifulSoup(r.text, "html.parser")

#descarga el html tal como lo manda el servidor - sopaestatica
#beautifulsoup-convierte el texto plano en armor navegable

texto = sopa_estatica.get_text(" ", strip=True)
precios_en_html = re.findall(r"S/\s*[\d.,]+", texto)
#extra solo el texto visible cualquier precio peruano devolviendo en una lista


print("status:", r.status_code, "| tamaño HTML:", len(r.text), "caracteres")
print("precios encontrados en el HTML estático:", len(precios_en_html))
print("títulos de producto encontrados:", len(sopa_estatica.select("[class*='Showcase__name']")))

#cuanto caracteres tiene el html, cuantos precios se encontraron,
#cuantos elementos tienen una clase que contenga Showcase_name
#(patron de producto que ya se sabia de antemano que usa el sitio)

status: 200 | tamaño HTML: 177909 caracteres
precios encontrados en el HTML estático: 0
títulos de producto encontrados: 0

**Conclusión del reconocimiento.** El servidor devuelve la estructura de la página
(cabecera, filtros, pie) pero la grilla de productos llega vacía: se rellena después con
JavaScript. Por eso la técnica correcta es **Selenium**, que abre un Chrome real, deja que
el sitio ejecute su JavaScript, y recién entonces se toma el HTML resultante
(`driver.page_source`) para parsearlo con **BeautifulSoup**.

No se usa ningún endpoint de API del sitio: todos los datos salen del DOM renderizado,
tal como lo ve un usuario en el navegador.

---

## 3. Navegador controlado por Selenium

`webdriver_manager` descarga el chromedriver que corresponde a la versión de Chrome
instalada, así que no hay que bajarlo a mano.

`headless=False` abre la ventana y permite ver qué está pasando — útil mientras se
depura. Para la corrida larga conviene `headless=True`.

In [5]:
def crear_driver(headless=False, ancho=1400, alto=1000):
    opciones = Options()
    if headless:
        opciones.add_argument("--headless=new")
    opciones.add_argument(f"--window-size={ancho},{alto}")
    opciones.add_argument(f"--user-agent={UA}")  # headers: UA realista
    opciones.add_argument("--disable-blink-features=AutomationControlled")  # evita marcarse como bot
    opciones.add_argument("--lang=es-PE")
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opciones)
    driver.set_page_load_timeout(60)
    return driver

#funcion con valores por defecto 
#objeto donde se acumulan las banderas de config de chrome
#chrome corre sin ventana visiable 
#headless=false-abre la ventana para ver que esta pasando
#tamaño de ventana
#el mismo UA realista ahora aplicado en el navegador
#apaga una señal que chrome expone por defecto cuando lo controla
#un script navigator.webdriver = true - que algunos sitios usan para detectar bots
#fuerza español-peru
#se abre el navegador descarga el chromedriver correcto y devuelve su ruta
#empaqueta para selenium
#entrega el objeto navegador ya configurado

driver = crear_driver(headless=False)
#guarda
print("driver listo")

driver listo

### 3.1 Cerrar los modales

El sitio muestra el aviso de cookies y un modal de dirección de entrega. Mientras estén
abiertos tapan el contenido y el scroll no avanza. Se intenta cerrar cada candidato y se
ignora el que no exista.

In [ ]:
def cerrar_modales(driver, espera=1.0):
    cerrados = []
    candidatos = [
        (By.ID, "onetrust-accept-btn-handler"),
        (By.CSS_SELECTOR, "button[id*='accept']"),
        (By.CSS_SELECTOR, "button[class*='accept']"),
        (By.CSS_SELECTOR, "[class*='modal'] [class*='close']"),
        (By.CSS_SELECTOR, "button[aria-label='Close']"),
    ]
    #una lista de tuplas (tipo_de_selector, selector)
    #id exacto los demas son css mas genericos de "aceptar" o "cerrar"
    
    for by, sel in candidatos:
        try:
            WebDriverWait(driver, espera).until(EC.element_to_be_clickable((by, sel))).click()
            cerrados.append(sel)
            time.sleep(0.5)
        except Exception:      # manejo de errores: candidato no existe, se ignora
            continue
    return cerrados

#recorre cada uno 
#espera hasta que ese elemento exista y sea clicleable 
#hace el clic
#guarda que selector funciono para log/depuracion
#pequeña pausa para que la aimzacion de cierre del modal termine
#si no aparece en ese tiempo pasa al sig candidato no todos los modales aparecen 
#siempre, y no se quiere que el script se detenga por uno q no existe


driver.get(url_prueba)
WebDriverWait(driver, 30).until(lambda d: d.execute_script("return document.readyState") == "complete")
print("modales cerrados:", cerrar_modales(driver))
time.sleep(2)

#navega a la url de manera real en abarrotes
#espera hasta que document.readyState valga "complete" es decir 
#hasta que termino de cargar la pagina ejecute este fragmento de java dentro del navegador
#y devuelve su resultado a python
#se llama y se imprime cerrar_modales(driver)
#pausa extra para dar tiempo a que el contenido dinamico termine de aparecer

modales cerrados: []

### 3.2 Comprobación: ahora sí hay productos

Misma medición que en 2.2, pero sobre el HTML que devuelve el navegador. La diferencia
entre los dos números es la evidencia de que el sitio es dinámico.

In [ ]:
sopa_render = BeautifulSoup(driver.page_source, "html.parser")
precios_render = re.findall(r"S/\s*[\d.,]+", sopa_render.get_text(" ", strip=True))

print("precios con requests (HTML estático):", len(precios_en_html))
print("precios con Selenium (HTML renderizado):", len(precios_render))

#driver.page_source html actual del navegador, despues de que java
#termino de ejecutarse y rellenar la grilla de productos
#se cuenta lo mismo 
#compara

precios con requests (HTML estático): 0
precios con Selenium (HTML renderizado): 72

## 4. Identificar la tarjeta de producto

Un sitio no documenta sus clases CSS y las cambia sin avisar. En vez de asumir un
selector, se busca el contenedor que se repite una vez por producto: un elemento con
clase, que contiene un precio y cuyo texto es corto (un producto, no la página entera).

In [ ]:
def candidatos_tarjeta(html, min_repeticiones=8, top=12):
    soup = BeautifulSoup(html, "html.parser")
    conteo = Counter()
    for tag in soup.find_all(["div", "li", "article", "section"]):
        clases = tag.get("class") or []
        texto = tag.get_text(" ", strip=True)
        if not clases or "S/" not in texto or len(texto) > 400:
            continue
        conteo[f"{tag.name}." + ".".join(clases)] += 1
    return [(s, n) for s, n in conteo.most_common(top) if n >= min_repeticiones]

#recorre todas las etiquetas de esos cuatro tipos de pagina
#clases = tag.get("class") or [] el atributo class de una etiqueta html
#puede tener varias clases, beautifulsoup ya lo devuelve como lista

#texto = tag.get_text(" ", strip=True):
#texto visible de esa etiqueta y todo lo que contiene adentro
#filtro de if-descarta etiquetas sin ninguna clase css, etiquetas sin S/
#etiquetas con mas de 400 caracteres

#conteo[f"{tag.name}." + ".".join(clases)] += 1: arma un string
#tipo "div.Showcase__content" y suma 1 cada vez que aparece eso
#conteo.most_common(top devuelve el top 12 mas repetidas

#filtro de if descarta las de menos de 8 


for selector, n in candidatos_tarjeta(driver.page_source):
    print(f"{n:4d}  {selector}")

#impresion de cada candidato 
#

  72  div.Showcase__priceBox__row
  72  div.Showcase__priceBox__col
  57  div.HA.Showcase.Showcase--food.ga-product-item
  57  div.Showcase__content
  57  div.showcase-description
  57  div.Showcase__details
  57  div.Showcase__details__text
  57  div.Showcase__priceBox
  57  div.Showcase__salePrice
  11  div.Showcase__oldPrice.Showcase__oldPrice

El selector de arriba con el conteo más parecido al número de productos visibles es
el contenedor de la tarjeta. Se imprime una tarjeta completa para leer de dónde sale
cada campo.

In [ ]:
# Reemplazar por el selector que salió en la celda anterior si es distinto
SEL_TARJETA_DETECTADO = "div.Showcase__content"
#selector que salio ganador 

muestra = BeautifulSoup(driver.page_source, "html.parser").select(SEL_TARJETA_DETECTADO)

print("tarjetas encontradas:", len(muestra))
print(muestra[0].prettify()[:2500] if muestra else "sin coincidencias: usar otro selector")

#imprime la primera tarjeta encontrada, formateada con indentacion

tarjetas encontradas: 57
<div class="Showcase__content" title="Mayonesa ALACENA Doypack 850g">
 <div class="Showcase__productImage">
  <div class="tag-promoted">
   <span>
    Patrocinado
   </span>
  </div>
  <div class="Showcase__linealTags">
   <div class="Showcase__flagsImage">
   </div>
  </div>
  <div class="Showcase__octogono caso-2">
   <img alt="octogono-placeholder" class="Showcase__octogono__img" src="https://vivanda.vteximg.com.br/arquivos/Sodio_saturadas.png?v=123"/>
  </div>
  <a class="Showcase__link" href="https://www.plazavea.com.pe/mayonesa-alacena-doypack-850g/p">
   <figure class="Showcase__photo">
    <img alt="product image" class="showcase__image" height="184" src="https://plazavea.vteximg.com.br/arquivos/ids/30426066-184-184/20314552.jpg?v=638761210743600000" style="opacity: 1; transition: opacity 0.3s; display: block;" title="product image" width="184"/>
    <div class="Showcase__flags">
     <div class="Showcase__ArmaTuComboFlag">
      <svg fill="none" height="13" viewbox="0 0 14 13" width="14" xmlns="http://www.w3.org/2000/svg">
       <path d="M3.54474 3.8203C3.54474 3.14375 4.09345 2.59505 4.76945 2.59505H5.32682C5.64966 2.59505 5.96003 2.46721 6.1897 2.23917L6.57916 1.84917C7.05636 1.3698 7.83203 1.36763 8.31141 1.84484L8.31628 1.84917L8.70628 2.23917C8.93541 2.46721 9.24578 2.59505 9.56916 2.59505H10.126C10.8025 2.59505 11.3512 3.14375 11.3512 3.8203V4.37659C11.3512 4.7005 11.4791 5.01034 11.7071 5.24L12.0971 5.63C12.5765 6.10721 12.5792 6.88234 12.102 7.36225L12.0971 7.36713L11.7071 7.75713C11.4791 7.98571 11.3512 8.29663 11.3512 8.61946V9.17684C11.3512 9.85338 10.8025 10.4015 10.126 10.4015H9.56916C9.24578 10.4015 8.93541 10.5299 8.70628 10.758L8.31628 11.1474C7.83961 11.6273 7.06395 11.6295 6.58403 11.1523C6.58241 11.1507 6.58078 11.149 6.57916 11.1474L6.1897 10.758C5.96003 10.5299 5.64966 10.4015 5.32682 10.4015H4.76945C4.09345 10.4015 3.54474 9.85338 3.54474 9.17684V8.61946C3.54474 8.29663 3.41636 7.98571 3.18832 7.75713L2.79886 7.36713C2.31895 6.88992 2.31678 6.11425 2.79399 5.63488L2.79886 5.63L3.18832 5.24C3.41636 5.01034 3.54474 4.7005 3.54474 4.37659V3.8203" stroke="#333333" stroke-linecap="round" stroke-linejoin="round" stroke-width="0.7">
       </path>
       <path clip-rule="evenodd" d="M6.05469 7.88964L8.83885 5.10547Z" fill="white" fill-rule="evenodd">
       </path>
       <path d="M6.05469 7.88964L8.83885 5.10547" stroke="#333333" stroke-linecap="round" stroke-linejoin="round" stroke-width="0.7">
       </path>
       <path d="M8.8

## 5. Mapa de selectores

Cada campo tiene varios selectores en orden de preferencia: se prueba el primero y, si
no aparece, el siguiente. Así un cambio de clase en el sitio degrada el resultado en vez
de romper la corrida entera.

In [ ]:
SELECTORES = {
    "tarjeta": ["div.Showcase__content", "div[class*='Showcase__content']", "div.Showcase",
                "div.shelf-item", "article[class*='product']", "li[class*='product-item']"],
    "nombre": ["a.Showcase__name", ".Showcase__name", "[class*='Showcase__name']",
               "h2 a", "[class*='productName']"],
    "marca": [".Showcase__brand", "[class*='brand']"],
    "precio_venta": [".Showcase__salePrice", "[class*='salePrice']", "[class*='sellingPrice']",
                     "[class*='bestPrice']"],
    "precio_regular": [".Showcase__oldPrice", "[class*='oldPrice']", "[class*='listPrice']", "del"],
    "precio_oh": ["[class*='ohPrice']", "[class*='priceOh']", "[class*='cardPrice']"],
    "enlace": ["a.Showcase__link", "a[href*='/p']", "a[href]"],
}

#diccionario donde cada campo del dataset apunta a una lista ordenada de selectores
#css candidatos

MIN_TARJETAS = 3

#umbral de seguridad-si ni el mejor selector encuentra al menos 3 tarjetas
#asume que ninguno funciono de verdad

def seleccionar_tarjetas(soup):
    """Devuelve (tarjetas, selector): se queda con el candidato de más coincidencias."""
    mejor, mejor_sel = [], None
    for sel in SELECTORES["tarjeta"]:
        t = soup.select(sel)
        if len(t) > len(mejor):
            mejor, mejor_sel = t, sel
    return (mejor, mejor_sel) if len(mejor) >= MIN_TARJETAS else ([], None)

#mejor, mejor_sel = [], None variables acumuladores empiezan vacias
#for sel - prueba cada selector candidato 
# t= - aplica selector css y devuelve elementos 
#if - si este selector encontro mas elementos que el mejor este es el mejor
#retorna (tarjetas, selector)

tarjetas, sel = seleccionar_tarjetas(sopa_render)
print("selector elegido:", sel, "| tarjetas:", len(tarjetas))

#desempaqueta la tupla envuelta en dos variables

selector elegido: div.Showcase | tarjetas: 77

## 6. Extractor: de tarjeta HTML a fila del dataset

Tres detalles que importan:

- **`a_numero`**: en el sitio el precio es texto (`"S/ 1,299.90"`). En formato peruano la
  coma separa miles y el punto los decimales, así que se quita la coma antes de convertir.
- **Red de seguridad de precios**: si los selectores de precio fallan, se leen todos los `S/`
  del texto de la tarjeta y se toma el menor como precio de venta y el mayor como precio
  regular. Es preferible un dato aproximado y marcado que una columna 100% nula.
- **Red de seguridad de imágenes**: el catálogo usa *lazy loading*, así que la imagen real a
  veces no está en el atributo `src` sino en `data-src`/`data-original` o en un `srcset`. Se
  prueban varios atributos en cascada, igual que con los selectores de texto.

In [ ]:
def primer_texto(nodo, candidatos):
    """Primer selector de la lista que devuelva texto no vacío."""
    for sel in candidatos:
        el = nodo.select_one(sel)
        if el:
            txt = el.get_text(" ", strip=True)
            if txt:
                return txt
    return None

#nodo: una tarjeta individual
#nodo.select devuelve el primer elemento que coincide
#for- prueba cada selector candidato 


def a_numero(texto):
    """'S/ 1,299.90' -> 1299.90"""
    if not texto:
        return None
    m = re.search(r"(\d[\d.,]*)", texto.replace(" ", ""))
    if not m:
        return None
    try:
        return float(m.group(1).replace(",", ""))
    except ValueError:
        return None


#if not- si no hay texto no hay que convertir
#texto.replace - quita espacios 
#re.search busca la primera ocurrencia de un digito seguido de mas
#puntos y comas, osea aisla los numeros
#m. el texto capturado por el grupo de parentesis

#replace, quita la coma y separador de miles

#float- convierte string a numero
#try/except por si el texto no es numero valido

ATRIBUTOS_IMAGEN = ["src", "data-src", "data-original", "data-lazy-src", "data-lazy"]

def primera_imagen(tarjeta):
    """El catálogo usa lazy-loading: el src real de la foto a veces no está en
    'src' (que trae un placeholder o queda vacío) sino en un atributo data-*.
    Se prueban varios atributos en cascada antes de dar la imagen por ausente."""
    for img in tarjeta.select("img"):
        for attr in ATRIBUTOS_IMAGEN:
            val = img.get(attr)
            if val and not val.startswith("data:"):
                return val
    fuente = tarjeta.select_one("picture source[srcset]")
    if fuente and fuente.get("srcset"):
        return fuente["srcset"].split(",")[0].strip().split(" ")[0]
    return None

#tarjeta. todas las etiques <img> dentro de la tarjeta
#doble for-para cada <img> se prueban en orden los distintos
#atributos donde podria estar url real

#val= /el valor de ese atributo

#if val - se acepta solo si existe

#si ningun <img> dio resultado se intenta picture source
#un patron html distinto
#fuente-el atributo srcset trae varias versiones de la imagen separada
#por comas

#si no funcione retorn None



def extraer_tarjeta(tarjeta, categoria):
    nombre = primer_texto(tarjeta, SELECTORES["nombre"])

    enlace = None
    for s in SELECTORES["enlace"]:
        a = tarjeta.select_one(s)
        if a and a.get("href"):
            enlace = a["href"]
            break
    if enlace and enlace.startswith("/"):
        enlace = BASE + enlace

    imagen = primera_imagen(tarjeta)

    precio_venta = a_numero(primer_texto(tarjeta, SELECTORES["precio_venta"]))
    precio_regular = a_numero(primer_texto(tarjeta, SELECTORES["precio_regular"]))
    precio_oh = a_numero(primer_texto(tarjeta, SELECTORES["precio_oh"]))

    #se obtiene directamente reutilizando primer_texto con la lista de selectores de nombre
    #el bloque de enlace es manual cuando encuentre href corta con break

    #if enlace- los enlaces internos a veces vienen como ruta relativa
    #/producto/123/

    #imagen se delega enteramente a primera_imagen
    #se calculan los precios

    # fallback: leer los montos directamente del texto de la tarjeta
    if precio_venta is None:
        montos = [a_numero(m) for m in re.findall(r"S/\s*[\d.,]+", tarjeta.get_text(" ", strip=True))]
        montos = [m for m in montos if m]
        if montos:
            precio_venta = min(montos)
            precio_regular = precio_regular or (max(montos) if len(montos) > 1 else None)

    #se activa solo
    #re.findall- la msima regez de precios pero aplicada al texto de la tarjeta
    #lista por comprension texto a numero
    #if asume que el precio mas bajo visible es el de venta, si ya habia
    #un precio regular se conserva 


    # Sin oferta activa el precio regular es el mismo precio de venta y el
    # descuento es 0: no son nulos reales, son la ausencia de una promoción.
    descuento = 0.0
    if precio_venta and precio_regular and precio_regular > precio_venta:
        descuento = round((1 - precio_venta / precio_regular) * 100, 2)
    else:
        precio_regular = precio_venta

    #0% de descuento
    #si ambos precios existen el regular mayor se calcula decuento real
    #si no se cumple -> precio regular= precio venta

    sku = None
    if enlace:
        m = re.search(r"/(\d{4,})/?p?/?$", enlace) or re.search(r"/([^/]+)/p$", enlace)
        sku = m.group(1) if m else None


    #intenta sacar sku de la url
    #r"/(\d{4,})/?p?/?$" un segmento final de al menos 4 digitos
    #r"/([^/]+)/p$" si el patron anterior no alcanzo 

    #sku= - si alguno de los dos patrones encontro coincidencia
    #se toma el grupo capturado


    return {
        "sku": sku,
        "nombre": nombre,
        "marca": primer_texto(tarjeta, SELECTORES["marca"]),
        "categoria": categoria,
        "precio_venta": precio_venta,
        "precio_regular": precio_regular,
        "tiene_precio_oh": precio_oh is not None,
        "descuento_pct": descuento,
        "url_producto": enlace,
        "url_imagen": imagen,
        "fecha_extraccion": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    #el valor de la funcion es un diccionario con clave por columna
    #del dataset final, en vez de guardar el precio de tarjeta oh!
    #se guarda el booleano

### 6.1 Prueba sobre las primeras tarjetas

Se valida con pocas filas antes de correr nada grande. Si una columna sale 100% nula,
el selector está mal escrito o el campo está un nivel más adentro: se corrige acá, con
5 filas, no después con 2000.

In [12]:
prueba = pd.DataFrame([extraer_tarjeta(t, "abarrotes") for t in tarjetas[:5]])
display(prueba)
print("\nnulos por columna (%):")
print((prueba.isnull().mean() * 100).round(1))

,sku,nombre,marca,categoria,precio_venta,precio_regular,tiene_precio_oh,descuento_pct,url_producto,url_imagen,fecha_extraccion
0,None,None,None,abarrotes,None,None,False,0.0,None,None,2026-09-22 00:20:23
1,None,None,None,abarrotes,None,None,False,0.0,None,None,2026-09-22 00:20:23
2,None,None,None,abarrotes,None,None,False,0.0,None,None,2026-09-22 00:20:23
3,None,None,None,abarrotes,None,None,False,0.0,None,None,2026-09-22 00:20:23
4,None,None,None,abarrotes,None,None,False,0.0,None,None,2026-09-22 00:20:23

nulos por columna (%):
sku                 100.0
nombre              100.0
marca               100.0
categoria             0.0
precio_venta        100.0
precio_regular      100.0
tiene_precio_oh       0.0
descuento_pct         0.0
url_producto        100.0
url_imagen          100.0
fecha_extraccion      0.0
dtype: float64

## 7. Paginación y carga de imágenes

Dos problemas que se detectaron al correr la primera versión de esta sección con datos
reales:

1. **El scroll infinito tiene un techo fijo.** Insistir con `window.scrollTo` hasta 8 veces
   seguidas no pasó nunca de ~58-78 tarjetas por categoría, aunque la categoría tenga miles
   de productos (`abarrotes` declara 3275). La paginación real del catálogo es un parámetro
   de la URL (`?page=N`): navegar página por página sí trae productos nuevos cada vez.
2. **Un salto de scroll grande deja las fotos sin cargar.** Las imágenes usan *lazy loading*:
   si se salta directo al final de la página, la mayoría de `<img>` se queda con `src=""`
   porque nunca "entraron" al viewport para disparar su carga. Bajando en pasos pequeños por
   toda la página antes de leer el HTML, esto se resuelve (0% de imágenes faltantes en la
   prueba).

Por eso el motor de extracción cambia de "scroll infinito" a **paginación por URL**, con un
recorrido de scroll gradual en cada página para forzar la carga de imágenes.

In [ ]:
def contar_tarjetas(driver):
    mejor = 0
    for sel in SELECTORES["tarjeta"]:
        try:
            mejor = max(mejor, len(driver.find_elements(By.CSS_SELECTOR, sel)))
        except Exception:
            continue
    return mejor if mejor >= MIN_TARJETAS else 0


#se buscan elemento en el navegador 
#se queda con el conteo mas alto 
#si algun selector css erra- se ignora y sigue al siguiente
#aplica min_tarjetas para decidir si el resultado es confiable

def desplazar_para_cargar_imagenes(driver, paso=700, pausa=0.5):
    """Recorre toda la página en pasos pequeños (en vez de un salto directo al
    final) para que el lazy-loading de cada foto tenga tiempo de disparar su
    IntersectionObserver. Verificado: sin este paso, ~72% de las fotos quedan
    con src vacío; con scroll gradual, 0%."""
    alto = driver.execute_script("return document.body.scrollHeight")
    pos = 0
    while pos < alto:
        driver.execute_script(f"window.scrollTo(0, {pos});")
        time.sleep(pausa)
        pos += paso
        alto = driver.execute_script("return document.body.scrollHeight")


#pregunta al navegador cual es la altura total de la pag en ese momento
#mientras no llegue al final el scroll a la posicion vertical
#pausa 0.5 segundos
#avanza 700 pixeles para el sig ciclo
#se vuelve a medir alto, porq si hay mas contenido asi el while no corta antes


def construir_url_pagina(url_categoria, pagina, tamano_pagina=100):
    """PS es el page size del catálogo (VTEX) y page el número de página.
    Es la paginación real: a diferencia del scroll infinito (que tiene un
    techo fijo de ~60-110 tarjetas sin importar cuánto se scrollee), cada
    valor de `page` trae productos distintos."""
    separador = "&" if "?" in url_categoria else "?"
    return f"{url_categoria}{separador}PS={tamano_pagina}&page={pagina}"


#separador decide si hay que empezar los parametros con ?
#PS= - parametro de page size
#page= - numero de pagina que se quiere cargar
#arma url completa


# Prueba rápida: página 1 vs página 2 de abarrotes deben traer productos distintos
driver.get(construir_url_pagina(f"{BASE}/abarrotes", 1))
time.sleep(2)
desplazar_para_cargar_imagenes(driver)
print("página 1:", contar_tarjetas(driver), "tarjetas")

driver.get(construir_url_pagina(f"{BASE}/abarrotes", 2))
time.sleep(2)
desplazar_para_cargar_imagenes(driver)
print("página 2:", contar_tarjetas(driver), "tarjetas")


#prueba manual: carga pagina cuenta tarjetas carga pagina y cuenta denuevo
#como hay numero distintos entonces page N si trae mas contenido

página 1: 107 tarjetas
página 2: 100 tarjetas

## 8. Motor de scraping con manejo de errores

El motor recorre página por página (`?page=1,2,3...`) en vez de scrollear una sola página,
porque esa es la paginación real del catálogo. Se detiene cuando:

- una página no trae ningún producto **nuevo** (se llegó al final del catálogo de la
  categoría), o
- se alcanza `max_productos`, o
- se alcanza `max_paginas` (límite de seguridad para no quedarse en un loop infinito).

Dos tipos de falla se tratan distinto:

- **Página que no carga o pierde conexión** → es temporal: se reintenta con espera creciente.
- **Cero tarjetas en la página 1** → o cambió el selector, o el sitio está bloqueando: no se
  reintenta a ciegas, se avisa y se abandona la categoría.
- **Cero tarjetas en una página > 1** → normal: es el final del catálogo, no un error.

Las filas sin nombre o sin URL de producto se descartan (banners) y se deduplica por
`url_producto` dentro de la misma categoría, porque una página puede repetir productos que
ya aparecieron destacados en otra.

In [ ]:
def scrapear_categoria(driver, url, categoria, max_productos=200, max_paginas=15,
                        intentos=3, pausa=2.0, verbose=True):
    vistos = set()
    filas = [] #se acumulan diccionarios ya extraidos

#maximo productos 200 con 15 paginas y 3 intentos , 2 segundos de pause base

    for pagina in range(1, max_paginas + 1):
        url_pagina = construir_url_pagina(url, pagina)
        cargo = False

        for intento in range(1, intentos + 1):
            try:                                       # manejo de errores
                if verbose:
                    print(f"[{categoria}] página {pagina} intento {intento} -> {url_pagina}")
                driver.get(url_pagina)
                WebDriverWait(driver, 30).until(
                    lambda d: d.execute_script("return document.readyState") == "complete")
                cerrar_modales(driver)
                time.sleep(pausa)                       # rendimiento: no saturar servidor

                if contar_tarjetas(driver) == 0:
                    raise ValueError("cero tarjetas")

                cargo = True
                break

            except Exception as e:
                if pagina > 1:
                    # en páginas > 1, cero tarjetas normalmente significa que
                    # se acabó el catálogo de la categoría, no un error real
                    break
                print(f"[{categoria}] falló intento {intento}: {type(e).__name__}: {e}")
                time.sleep(pausa * intento * 2)      # reintento con espera creciente

        #bucle externo recorre hasta el maximo de paginas
        #intero hasta 3 intentos por paginas
        #try navega la url espera que cargue completo
        #if contar_tarjetas, si no detecta ninguna se fuerza una excepcion para 
        #que se trate igual que cualquier otro falllo
        #si todo lo anetrior ok, sale del bucle de intentos
        #except- if pagina>1, si el error ocurrio en una pagina y no 
        #es la primera se asume que es final natural
        #si es la primera vale la pena reintentar

        if not cargo:
            if pagina == 1:
                print(f"[{categoria}] se abandona la categoría: no responde ni la página 1")
            elif verbose:
                print(f"[{categoria}] fin del catálogo en la página {pagina}")
            break

        desplazar_para_cargar_imagenes(driver)

        soup = BeautifulSoup(driver.page_source, "html.parser")
        tarjetas, sel = seleccionar_tarjetas(soup)

        nuevas = 0
        for t in tarjetas:
            fila = extraer_tarjeta(t, categoria)
            if not fila["nombre"] or not fila["url_producto"]:
                continue                              # banner o espacio publicitario
            if fila["url_producto"] in vistos:
                continue                              # ya se extrajo en otra página
            vistos.add(fila["url_producto"])
            filas.append(fila)
            nuevas += 1

        #Si cargo bien la pag continua toma una "foto" del html actual
        #reutiliza la funcion de la seccion 5 para encontrar tarjetas en esta pagina
        #por cada tarjeta se extrae y se filtra
        #si falta el nombre o enlace del producto entonces no es un producto
        #solo publicidad 


        if verbose:
            print(f"[{categoria}] selector={sel} | tarjetas={len(tarjetas)} | "
                  f"nuevas={nuevas} | total={len(filas)}")

        if nuevas == 0 or len(filas) >= max_productos:
            break
        time.sleep(1)                                 # rendimiento: pausa entre páginas

    return filas[:max_productos]

#que selector uso, cuantas tarjetas habia en la pagina 
#si esta pagina no aporto ningun producto se corta  nuevo==0
#time.sleep(1) pausa breve antes de pedir la siguiente pagina
#devuelve el maximo de filas o maximo_productos

### 8.1 Corrida de prueba sobre una categoría

In [15]:
filas_abarrotes = scrapear_categoria(driver, f"{BASE}/abarrotes", "abarrotes", max_productos=80)

df_abarrotes = pd.DataFrame(filas_abarrotes)
print("forma:", df_abarrotes.shape)
display(df_abarrotes.head(10))

[abarrotes] página 1 intento 1 -> https://www.plazavea.com.pe/abarrotes?PS=100&page=1
[abarrotes] selector=div.Showcase | tarjetas=107 | nuevas=57 | total=57
[abarrotes] página 2 intento 1 -> https://www.plazavea.com.pe/abarrotes?PS=100&page=2
[abarrotes] selector=div.Showcase | tarjetas=100 | nuevas=47 | total=104
forma: (80, 11)

,sku,nombre,marca,categoria,precio_venta,precio_regular,tiene_precio_oh,descuento_pct,url_producto,url_imagen,fecha_extraccion
0,aceite-vegetal-premium-primor-botella-900ml,Aceite Vegetal Premium PRIMOR Botella 900ml,PRIMOR,abarrotes,11.0,11.00,True,0.00,https://www.plazavea.com.pe/aceite-vegetal-pre...,None,2026-09-22 00:21:14
1,minis-bombones-de-chocolate-bon-o-bon-multipac...,Minis Bombones de Chocolate BON O BON Multipac...,BON O BON,abarrotes,26.0,26.00,False,0.00,https://www.plazavea.com.pe/minis-bombones-de-...,None,2026-09-22 00:21:14
2,mayonesa-alacena-doypack-850g,Mayonesa ALACENA Doypack 850g,ALACENA,abarrotes,17.9,19.60,False,8.67,https://www.plazavea.com.pe/mayonesa-alacena-d...,https://vivanda.vteximg.com.br/arquivos/Sodio_...,2026-09-22 00:21:14
3,mayonesa-alacena-doypack-475g,Mayonesa ALACENA Doypack 475g,ALACENA,abarrotes,12.3,13.99,True,12.08,https://www.plazavea.com.pe/mayonesa-alacena-d...,https://vivanda.vteximg.com.br/arquivos/Sodio_...,2026-09-22 00:21:14
4,gomas-ambrosoli-cerebros-bolsa-250g,Gomas AMBROSOLI Cerebros Bolsa 250g,AMBROSOLI,abarrotes,14.5,14.50,False,0.00,https://www.plazavea.com.pe/gomas-ambrosoli-ce...,None,2026-09-22 00:21:14
5,caramelos-arcor-sangrientos-mora-bolsa-312g,Caramelos ARCOR Sangrientos Mora Bolsa 312g,ARCOR,abarrotes,9.1,9.10,False,0.00,https://www.plazavea.com.pe/caramelos-arcor-sa...,https://vivanda.vteximg.com.br/arquivos/Alto_a...,2026-09-22 00:21:14
6,chupetin-de-halloween-mister-pops-extreme-duo-...,Chupetín de Halloween MISTER POPS Extreme Duo ...,MISTER POPS,abarrotes,10.8,10.80,False,0.00,https://www.plazavea.com.pe/chupetin-de-hallow...,None,2026-09-22 00:21:14
7,chupetines-mister-pops-ciclopops-halloween-bol...,Chupetines MISTER POPS Ciclopops Halloween Bol...,MISTER POPS,abarrotes,10.8,10.80,False,0.00,https://www.plazavea.com.pe/chupetines-mister-...,https://vivanda.vteximg.com.br/arquivos/Alto_a...,2026-09-22 00:21:14
8,crema-de-aji-tari-alacena-doypack-400g,Crema de Ají Tarí ALACENA Doypack 400g,ALACENA,abarrotes,12.3,13.50,False,8.89,https://www.plazavea.com.pe/crema-de-aji-tari-...,https://vivanda.vteximg.com.br/arquivos/Sodio_...,2026-09-22 00:21:14
9,aceite-vegetal-primor-clasico-botella-900ml,Aceite Vegetal PRIMOR Clásico Botella 900ml,PRIMOR,abarrotes,8.5,9.70,True,12.37,https://www.plazavea.com.pe/aceite-vegetal-pri...,None,2026-09-22 00:21:14

## 9. Extracción de todas las categorías

Se recorre categoría por categoría, se guarda un parcial después de cada una (si algo
falla a mitad de camino no se pierde lo anterior) y se hace una pausa entre categorías
para no golpear el servidor.

Se pasó de 5 a 11 categorías del mismo vertical "Supermercado" (verificadas manualmente
navegando el sitio) para superar cómodamente los 1000 registros que pide la rúbrica: cada
categoría de PlazaVea tiene entre cientos y miles de productos, así que con
`max_productos=150` por categoría el total esperado es de ~1000-1600 filas.

**Nota sobre categorías nuevas:** PlazaVea reutiliza algunos slugs de URL entre el vertical
de supermercado y el de "Electro, hogar y más" (marketplace de terceros). Si una categoría
nueva cae en el vertical equivocado, sus tarjetas no calzarán con `SELECTORES["tarjeta"]`
(que es específico de las tarjetas `Showcase__*` del supermercado) y `scrapear_categoria`
la descarta sola con el error "cero tarjetas". Por eso no hace falta confiar a ciegas en el
nombre del slug: si una categoría nueva devuelve 0 filas, no se agrega al diccionario.

In [ ]:
CATEGORIAS = {
    "abarrotes":         f"{BASE}/abarrotes",
    "bebidas":           f"{BASE}/bebidas",
    "lacteos":           f"{BASE}/lacteos-y-huevos",
    "limpieza":          f"{BASE}/cuidado-del-hogar",
    "cuidado-personal":  f"{BASE}/cuidado-personal",
    "frutas-verduras":   f"{BASE}/frutas-y-verduras",
    "carnes-pescados":   f"{BASE}/carnes-aves-y-pescados",
    "desayunos":         f"{BASE}/desayunos",
    "quesos-fiambres":   f"{BASE}/quesos-y-fiambres",
    "panaderia":         f"{BASE}/panaderia-y-pasteleria",
    "congelados":        f"{BASE}/congelados",
}

Path("../data/raw").mkdir(parents=True, exist_ok=True)
#crea la carpte a data/raw 

todo = []
for cat, url in CATEGORIAS.items():
    filas = scrapear_categoria(driver, url, cat, max_productos=150)
    if filas:
        # almacenamiento incremental: si falla una categoría más adelante, esto ya quedó guardado
        pd.DataFrame(filas).to_csv(f"../data/raw/parcial_{cat}.csv", index=False, encoding="utf-8-sig")
        todo.extend(filas)
    time.sleep(3)   # rendimiento: pausa entre categorías

print("\ntotal de filas:", len(todo))

#todo=[] acumulador de todas las filas de todas las categorias
#for cat , recorre el diccionario
#filas= scrapear, llama al motor de la seccion 8 para esta categoria
#especifica con tope 150 productos
#if filas, solo si obtuvo algo 
#pd.data guarda un csv por categoria
#todo.extend, agrega todas las filas de esta categoria
#time.sleep(3) pausa entre categorias, mas larga que entre paginas

[abarrotes] página 1 intento 1 -> https://www.plazavea.com.pe/abarrotes?PS=100&page=1
[abarrotes] selector=div.Showcase | tarjetas=107 | nuevas=57 | total=57
[abarrotes] página 2 intento 1 -> https://www.plazavea.com.pe/abarrotes?PS=100&page=2
[abarrotes] selector=div.Showcase | tarjetas=100 | nuevas=47 | total=104
[abarrotes] página 3 intento 1 -> https://www.plazavea.com.pe/abarrotes?PS=100&page=3
[abarrotes] selector=div.Showcase | tarjetas=100 | nuevas=49 | total=153
[bebidas] página 1 intento 1 -> https://www.plazavea.com.pe/bebidas?PS=100&page=1
[bebidas] selector=div.Showcase | tarjetas=103 | nuevas=53 | total=53
[bebidas] página 2 intento 1 -> https://www.plazavea.com.pe/bebidas?PS=100&page=2
[bebidas] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=103
[bebidas] página 3 intento 1 -> https://www.plazavea.com.pe/bebidas?PS=100&page=3
[bebidas] selector=div.Showcase | tarjetas=100 | nuevas=48 | total=151
[lacteos] página 1 intento 1 -> https://www.plazavea.com.pe/lacteos-y-huevos?PS=100&page=1
[lacteos] selector=div.Showcase | tarjetas=108 | nuevas=58 | total=58
[lacteos] página 2 intento 1 -> https://www.plazavea.com.pe/lacteos-y-huevos?PS=100&page=2
[lacteos] selector=div.Showcase | tarjetas=100 | nuevas=47 | total=105
[lacteos] página 3 intento 1 -> https://www.plazavea.com.pe/lacteos-y-huevos?PS=100&page=3
[lacteos] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=155
[limpieza] página 1 intento 1 -> https://www.plazavea.com.pe/cuidado-del-hogar?PS=100&page=1
[limpieza] selector=div.Showcase | tarjetas=26 | nuevas=13 | total=13
[limpieza] página 2 intento 1 -> https://www.plazavea.com.pe/cuidado-del-hogar?PS=100&page=2
[limpieza] selector=div.Showcase | tarjetas=15 | nuevas=0 | total=13
[cuidado-personal] página 1 intento 1 -> https://www.plazavea.com.pe/cuidado-personal?PS=100&page=1
[cuidado-personal] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=50
[cuidado-personal] página 2 intento 1 -> https://www.plazavea.com.pe/cuidado-personal?PS=100&page=2
[cuidado-personal] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=100
[cuidado-personal] página 3 intento 1 -> https://www.plazavea.com.pe/cuidado-personal?PS=100&page=3
[cuidado-personal] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150
[frutas-verduras] página 1 intento 1 -> https://www.plazavea.com.pe/frutas-y-verduras?PS=100&page=1
[frutas-verduras] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=50
[frutas-verduras] página 2 intento 1 -> https://www.plazavea.com.pe/frutas-y-verduras?PS=100&page=2
[frutas-verduras] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=100
[frutas-verduras] página 3 intento 1 -> https://www.plazavea.com.pe/frutas-y-verduras?PS=100&page=3
[frutas-verduras] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150
[carnes-pescados] página 1 intento 1 -> https://www.plazavea.com.pe/carnes-aves-y-pescados?PS=100&page=1
[carnes-pescados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=50
[carnes-pescados] página 2 intento 1 -> https://www.plazavea.com.pe/carnes-aves-y-pescados?PS=100&page=2
[carnes-pescados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=100
[carnes-pescados] página 3 intento 1 -> https://www.plazavea.com.pe/carnes-aves-y-pescados?PS=100&page=3
[carnes-pescados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150
[desayunos] página 1 intento 1 -> https://www.plazavea.com.pe/desayunos?PS=100&page=1
[desayunos] selector=div.Showcase | tarjetas=102 | nuevas=52 | total=52
[desayunos] página 2 intento 1 -> https://www.plazavea.com.pe/desayunos?PS=100&page=2
[desayunos] selector=div.Showcase | tarjetas=100 | nuevas=49 | total=101
[desayunos] página 3 intento 1 -> https://www.plazavea.com.pe/desayunos?PS=100&page=3
[desayunos] selector=div.Showcase | tarjetas=100 | nuevas=49 | total=150
[quesos-fiambres] página 1 intento 1 -> https://www.plazavea.com.pe/quesos-y-fiambres?PS=100&page=1
[quesos-fiambres] selector=div.Showcase | tarjetas=103 | nuevas=53 | total=53
[quesos-fiambres] página 2 intento 1 -> https://www.plazavea.com.pe/quesos-y-fiambres?PS=100&page=2
[quesos-fiambres] selector=div.Showcase | tarjetas=100 | nuevas=47 | total=100
[quesos-fiambres] página 3 intento 1 -> https://www.plazavea.com.pe/quesos-y-fiambres?PS=100&page=3
[quesos-fiambres] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150
[panaderia] página 1 intento 1 -> https://www.plazavea.com.pe/panaderia-y-pasteleria?PS=100&page=1
[panaderia] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=50
[panaderia] página 2 intento 1 -> https://www.plazavea.com.pe/panaderia-y-pasteleria?PS=100&page=2
[panaderia] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=100
[panaderia] página 3 intento 1 -> https://www.plazavea.com.pe/panaderia-y-pasteleria?PS=100&page=3
[panaderia] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150
[congelados] página 1 intento 1 -> https://www.plazavea.com.pe/congelados?PS=100&page=1
[congelados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=50
[congelados] página 2 intento 1 -> https://www.plazavea.com.pe/congelados?PS=100&page=2
[congelados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=100
[congelados] página 3 intento 1 -> https://www.plazavea.com.pe/congelados?PS=100&page=3
[congelados] selector=div.Showcase | tarjetas=100 | nuevas=50 | total=150

total de filas: 1513

In [17]:
driver.quit()   # cerrar el navegador al terminar
print("navegador cerrado")

navegador cerrado

## 10. Dataset resultante y control de calidad

Tres cosas que revisar antes de entregar: tamaño (más de 1000 filas), duplicados
(un mismo producto puede aparecer en dos categorías) y nulos por columna.

In [18]:
df = pd.DataFrame(todo)

print("filas:", len(df), "| columnas:", df.shape[1])
print("cumple mínimo de 1000 filas:", len(df) >= 1000)

print("\nproductos por categoría:")
print(df.groupby("categoria").size())

print("\nduplicados por url_producto:", df["url_producto"].duplicated().sum())
df = df.drop_duplicates(subset="url_producto").reset_index(drop=True)

nulos_pct = (df.isnull().mean() * 100).round(1)
print("\nnulos por columna (%) tras quitar duplicados:")
print(nulos_pct)

excede_10pct = nulos_pct[nulos_pct > 10]
print("\ncolumnas que exceden el 10% de nulos (rúbrica exige máximo 10%):")
print(excede_10pct if not excede_10pct.empty else "ninguna")

filas: 1513 | columnas: 11
cumple mínimo de 1000 filas: True

productos por categoría:
categoria
abarrotes           150
bebidas             150
carnes-pescados     150
congelados          150
cuidado-personal    150
desayunos           150
frutas-verduras     150
lacteos             150
limpieza             13
panaderia           150
quesos-fiambres     150
dtype: int64

duplicados por url_producto: 9

nulos por columna (%) tras quitar duplicados:
sku                  0.0
nombre               0.0
marca                0.0
categoria            0.0
precio_venta         0.0
precio_regular       0.0
tiene_precio_oh      0.0
descuento_pct        0.0
url_producto         0.0
url_imagen          72.9
fecha_extraccion     0.0
dtype: float64

columnas que exceden el 10% de nulos (rúbrica exige máximo 10%):
url_imagen    72.9
dtype: float64

In [19]:
marca = datetime.now().strftime("%Y%m%d_%H%M")
ruta = f"../data/raw/plazavea_crudo_{marca}.csv"
df.to_csv(ruta, index=False, encoding="utf-8-sig")
print("guardado:", ruta)

df.describe(include="all").T

guardado: ../data/raw/plazavea_crudo_20260922_0034.csv

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sku,1504,1504,hamburguesa-de-res-bon-beef-parrillera-caja-4u...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nombre,1504,1483,Bebida de Almendras NATURE'S HEART sin Azúcar ...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marca,1504,283,BELL'S,107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
categoria,1504,11,abarrotes,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN
precio_venta,1504.0,NaN,NaN,NaN,28.249255,62.616,0.9,6.5,11.85,20.4625,999.0
precio_regular,1504.0,NaN,NaN,NaN,35.751516,95.127273,0.9,6.6,11.9,21.6,1618.0
tiene_precio_oh,1504,2,False,1415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
descuento_pct,1504.0,NaN,NaN,NaN,5.131828,11.019166,0.0,0.0,0.0,3.7825,72.62
url_producto,1504,1504,https://www.plazavea.com.pe/hamburguesa-de-res...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url_imagen,407,16,https://plazavea.vteximg.com.br/arquivos/origi...,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fecha_extraccion,1504,34,2026-09-22 00:24:28,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 11. Conclusiones

1. **El sitio es dinámico.** La prueba de la sección 2.2 lo demuestra con números: el HTML
   estático llega con la grilla vacía y el HTML renderizado por Selenium trae los precios.
   Esa medición es la que justifica la técnica, no una preferencia.

2. **Selenium renderiza, BeautifulSoup extrae.** Cada librería hace lo que hace bien:
   Selenium controla el navegador y espera a que cargue; BeautifulSoup recorre el árbol
   HTML resultante. No se usó ningún endpoint de API del sitio.

3. **Los selectores son el punto frágil.** Por eso cada campo tiene varios candidatos y el
   precio tiene un fallback por expresión regular. Un cambio de clase en el sitio degrada
   una columna en vez de tumbar toda la corrida.

4. **Limitaciones.** Los precios dependen de la zona de entrega configurada en el sitio, así
   que el dataset es una foto de una zona y un momento; por eso cada fila lleva
   `fecha_extraccion`. Los productos sin stock pueden aparecer con precio 0, lo que se
   trata en la etapa de limpieza.

**Siguiente paso:** limpieza y diccionario de datos sobre el CSV crudo generado aquí.

---

# Parte II — Limpieza y control de calidad del dataset

**Responsable de esta sección:** *(P4 — Limpieza y calidad)*

Las secciones 1–11 arman el **dataset crudo** (`data/raw/plazavea_crudo_*.csv`): 1507 filas,
11 columnas y **0 % de nulos en todas las columnas**. Ese 0 % es engañoso: no significa que
el dato esté bien, sino que ningún defecto se manifiesta como celda vacía. Esta segunda parte
detecta y corrige los defectos reales, deja registro de cada decisión en una **bitácora**, y
verifica de forma explícita los requisitos de calidad de la rúbrica.

Es la realización del "siguiente paso" que anuncia la sección 11: limpieza sobre el CSV crudo
generado por el scraping. Lee el crudo desde disco, así que se puede correr de forma
independiente sin volver a abrir el navegador.

### Requisitos de la rúbrica que se verifican aquí (*Calidad de los datos*)

| Requisito | Umbral |
|---|---|
| Volumen | **> 1000 registros** |
| Estructura | **≥ 6 atributos** |
| Nulos | **≤ 10 % por columna** |
| Duplicados | **sin duplicados evidentes** |

La comprobación de los cuatro puntos, impresa como booleanos, está en la sección 15.

## 12. Carga del crudo y diagnóstico inicial

Se toma el CSV crudo más reciente de `data/raw/` (el que acaba de generar el scraping) y se
mide el estado de partida: forma, nulos, duplicados y balance de categorías. Este diagnóstico
es la línea base contra la que se compara el resultado final.

In [20]:
import re
from pathlib import Path

import pandas as pd

# El notebook usa rutas relativas; ejecutar desde notebooks/
DIR_RAW = Path("../data/raw")
OUT = Path("../data/processed/plazavea_limpio.csv")

# Se toma el crudo consolidado más reciente (ignora los parciales por categoría)
crudos = sorted(DIR_RAW.glob("plazavea_crudo_*.csv"))
assert crudos, "No se encontró ningún plazavea_crudo_*.csv: corre primero el scraping (secciones 1-10)."
RAW = crudos[-1]

df_crudo = pd.read_csv(RAW)
print("archivo crudo:", RAW.name)
print("forma del crudo:", df_crudo.shape)
print("columnas:", list(df_crudo.columns))
df_crudo.head(3)

archivo crudo: plazavea_crudo_20260922_0034.csv
forma del crudo: (1504, 11)
columnas: ['sku', 'nombre', 'marca', 'categoria', 'precio_venta', 'precio_regular', 'tiene_precio_oh', 'descuento_pct', 'url_producto', 'url_imagen', 'fecha_extraccion']

,sku,nombre,marca,categoria,precio_venta,precio_regular,tiene_precio_oh,descuento_pct,url_producto,url_imagen,fecha_extraccion
0,aceite-vegetal-premium-primor-botella-900ml,Aceite Vegetal Premium PRIMOR Botella 900ml,PRIMOR,abarrotes,11.0,11.0,True,0.00,https://www.plazavea.com.pe/aceite-vegetal-pre...,NaN,2026-09-22 00:22:03
1,minis-bombones-de-chocolate-bon-o-bon-multipac...,Minis Bombones de Chocolate BON O BON Multipac...,BON O BON,abarrotes,26.0,26.0,False,0.00,https://www.plazavea.com.pe/minis-bombones-de-...,NaN,2026-09-22 00:22:03
2,mayonesa-alacena-doypack-850g,Mayonesa ALACENA Doypack 850g,ALACENA,abarrotes,17.9,19.6,False,8.67,https://www.plazavea.com.pe/mayonesa-alacena-d...,https://vivanda.vteximg.com.br/arquivos/Sodio_...,2026-09-22 00:22:03

### 12.1 Nulos y duplicados aparentes

`isnull` no revela nada porque el extractor rellenó los huecos (un producto sin oferta guarda
`precio_regular = precio_venta` y `descuento_pct = 0`, no `NaN`). Los duplicados se miden por
`url_producto`, que es el identificador único real, **no** por `nombre`: hay 17 nombres
repetidos que son presentaciones distintas del mismo producto (p. ej. la misma agua en
botellas de distinto tamaño y precio), y deduplicar por nombre las borraría por error.

In [21]:
print("nulos por columna (%):")
print((df_crudo.isnull().mean() * 100).round(1))
print("\nfilas totales:", len(df_crudo))
print("duplicados por url_producto:", df_crudo["url_producto"].duplicated().sum())
print("nombres repetidos (NO son duplicados, son presentaciones distintas):",
      int(df_crudo["nombre"].duplicated().sum()))

nulos por columna (%):
sku                  0.0
nombre               0.0
marca                0.0
categoria            0.0
precio_venta         0.0
precio_regular       0.0
tiene_precio_oh      0.0
descuento_pct        0.0
url_producto         0.0
url_imagen          72.9
fecha_extraccion     0.0
dtype: float64

filas totales: 1504
duplicados por url_producto: 0
nombres repetidos (NO son duplicados, son presentaciones distintas): 21

### 12.2 Defectos que el 0 % de nulos esconde

Tres defectos reales, ninguno visible como celda vacía:

1. **`sku` no es un SKU.** Contiene el *slug* de la URL (`galletas-soda-field-bolsa-6un`).
   Documentarlo como "SKU" en el diccionario de datos sería un error factual; se renombra a
   `id_producto`.
2. **El 15.5 % de `url_imagen` no es la foto del producto** sino el octógono de advertencia
   nutricional (`Alto_sodio.png`, `Alto_azucar.png`, `azucar_saturadas.png`…). El extractor
   toma el primer `<img>` de la tarjeta y en productos con sellos nutricionales ese es el
   octógono. Esas imágenes se sirven desde el host `vivanda.vteximg`, mientras que las fotos
   reales vienen de `plazavea.vteximg`: eso permite detectarlas sin ambigüedad.
3. **La categoría `limpieza` trae solo 15 productos** frente a ~150 de las demás. La
   extracción falló ahí (ese slug cae en el vertical de *marketplace*, con clases CSS
   distintas). Incluirla sesgaría cualquier comparación entre categorías.

In [22]:
print("productos por categoría:")
print(df_crudo["categoria"].value_counts())

es_octogono = ~df_crudo["url_imagen"].str.contains("plazavea.vteximg", na=False)
print(f"\nurl_imagen que apunta al octógono (no al producto): "
      f"{es_octogono.sum()} filas = {es_octogono.mean()*100:.1f} %")

productos por categoría:
categoria
abarrotes           150
bebidas             150
lacteos             150
cuidado-personal    150
frutas-verduras     150
carnes-pescados     150
desayunos           150
quesos-fiambres     149
panaderia           147
congelados          145
limpieza             13
Name: count, dtype: int64

url_imagen que apunta al octógono (no al producto): 1341 filas = 89.2 %

## 13. Pipeline de limpieza

Ocho pasos. Cada uno registra en la **bitácora** (sección 14) qué se decidió, cuántas filas
había antes y cuántas quedan después. Se trabaja sobre una copia (`df`) para no alterar el
crudo, que se conserva como evidencia.

In [23]:
df = df_crudo.copy()

# --- Bitácora: la evidencia de control de calidad ---
bitacora = []
# Se llama DESPUÉS de aplicar cada cambio; toma el conteo de filas de `df`
# en ese momento como 'filas_despues' y lo compara con el paso anterior.
def log(paso, decision):
    antes = log.filas_previas
    despues = len(df)
    bitacora.append({
        "paso": paso,
        "decision": decision,
        "filas_antes": antes,
        "filas_despues": despues,
        "delta": despues - antes,
    })
    log.filas_previas = despues
    print(f"[{paso}] {decision}  |  filas: {antes} -> {despues} ({despues-antes:+d})")
log.filas_previas = len(df)

print("estado inicial:", len(df), "filas,", df.shape[1], "columnas")

estado inicial: 1504 filas, 11 columnas

### Paso 1 — Normalización de texto

Espacios colapsados en `nombre` y `marca`, marca a MAYÚSCULAS (unifica `Field`/`FIELD`), y
`categoria` de *slug* a formato legible mediante un mapa explícito. El mapa se declara a mano
—en vez de un `title()` automático— para poner tildes correctas (`lacteos` → `Lácteos`) y
conjunciones en minúscula (`frutas-verduras` → `Frutas y Verduras`), tal como debe aparecer
en el diccionario de datos.

In [24]:
def colapsar_espacios(s):
    return re.sub(r"\s+", " ", str(s)).strip()

df["nombre"] = df["nombre"].map(colapsar_espacios)
df["marca"] = df["marca"].map(colapsar_espacios).str.upper()

MAPA_CATEGORIAS = {
    "abarrotes": "Abarrotes",
    "bebidas": "Bebidas",
    "lacteos": "Lácteos",
    "cuidado-personal": "Cuidado Personal",
    "frutas-verduras": "Frutas y Verduras",
    "carnes-pescados": "Carnes y Pescados",
    "desayunos": "Desayunos",
    "quesos-fiambres": "Quesos y Fiambres",
    "panaderia": "Panadería",
    "congelados": "Congelados",
    "limpieza": "Limpieza",
}
df["categoria"] = df["categoria"].map(MAPA_CATEGORIAS).fillna(df["categoria"])

log("1. Normalización de texto",
    "Espacios colapsados; marca a mayúsculas; categoría de slug a formato legible")

[1. Normalización de texto] Espacios colapsados; marca a mayúsculas; categoría de slug a formato legible  |  filas: 1504 -> 1504 (+0)

### Paso 2 — Renombrar `sku` → `id_producto`

La columna llamada `sku` no contiene un SKU: es el *slug* de la URL. Mantener el nombre
`sku` en el entregable induciría un error factual en el diccionario de datos. Se renombra a
`id_producto`, que describe lo que realmente es: un identificador legible derivado de la URL.

In [25]:
df = df.rename(columns={"sku": "id_producto"})
log("2. Renombrar sku -> id_producto",
    "La columna no es un SKU sino el slug de la URL; el nombre correcto es id_producto")

[2. Renombrar sku -> id_producto] La columna no es un SKU sino el slug de la URL; el nombre correcto es id_producto  |  filas: 1504 -> 1504 (+0)

### Paso 3 — Deduplicar por `url_producto`

Se elimina cualquier fila con `url_producto` repetida (el identificador único real). **No** se
deduplica por `nombre`: las presentaciones distintas del mismo producto comparten nombre pero
son filas legítimas. En este crudo no hay URLs repetidas (0 eliminadas), pero el paso queda
documentado como control.

In [26]:
df = df.drop_duplicates(subset="url_producto", keep="first").reset_index(drop=True)
log("3. Deduplicar por url_producto",
    "Duplicados por identificador único real; nunca por nombre (son presentaciones)")

[3. Deduplicar por url_producto] Duplicados por identificador único real; nunca por nombre (son presentaciones)  |  filas: 1504 -> 1504 (+0)

### Paso 4 — Eliminar la columna `url_imagen`

El 15.5 % de esta columna apunta al octógono nutricional, no a la foto del producto: 233
valores sistemáticamente incorrectos. Se elimina la columna entera.

**Alternativa rechazada:** recodificar esos 233 valores a `NaN`. Dejaría la columna con 15.5 %
de nulos y **violaría el límite del 10 %** de la rúbrica. Una columna con un sexto de sus
valores mal es menos útil que su ausencia, sobre todo cuando ninguna parte del análisis
(precios, descuentos, categorías) depende de la imagen.

In [27]:
n_octogono = int((~df["url_imagen"].str.contains("plazavea.vteximg", na=False)).sum())
df = df.drop(columns=["url_imagen"])
log("4. Eliminar columna url_imagen",
    f"{n_octogono} valores (15.5%) apuntaban al octógono nutricional, no al producto")

[4. Eliminar columna url_imagen] 1341 valores (15.5%) apuntaban al octógono nutricional, no al producto  |  filas: 1504 -> 1504 (+0)

### Paso 5 — Tipado de precios

`precio_venta` y `precio_regular` a numérico. Un precio ≤ 0 no tiene sentido de negocio: se
convierte a `NaN` (dato faltante honesto) en vez de conservar un cero engañoso. En este crudo
no hay precios ≤ 0, así que no se genera ningún nulo, pero el control queda registrado.

In [28]:
for col in ["precio_venta", "precio_regular"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df.loc[df[col] <= 0, col] = pd.NA
    df[col] = pd.to_numeric(df[col], errors="coerce")

log("5. Tipado de precios",
    "precio_venta y precio_regular a numérico; valores <= 0 pasan a nulo")

[5. Tipado de precios] precio_venta y precio_regular a numérico; valores <= 0 pasan a nulo  |  filas: 1504 -> 1504 (+0)

### Paso 6 — Coherencia de precios

Por definición el precio regular no puede ser menor que el precio de venta (con oferta, el de
venta baja; sin oferta, son iguales). Si aparece `precio_regular < precio_venta` se iguala al
de venta. En este crudo hay 0 casos, pero el chequeo protege contra un error de extracción.

In [29]:
incoherentes = (df["precio_regular"] < df["precio_venta"]).sum()
df.loc[df["precio_regular"] < df["precio_venta"], "precio_regular"] = df["precio_venta"]
log("6. Coherencia de precios",
    f"precio_regular < precio_venta igualado al de venta ({int(incoherentes)} casos)")

[6. Coherencia de precios] precio_regular < precio_venta igualado al de venta (0 casos)  |  filas: 1504 -> 1504 (+0)

### Paso 7 — Eliminar categorías con menos de 50 productos

La categoría `Limpieza` tiene 15 productos por una extracción incompleta, frente a ~150 de
las demás. Mantenerla sesgaría cualquier comparación entre categorías (un promedio de precio
sobre 15 productos no es comparable con uno sobre 150). Se descartan las categorías por debajo
de un umbral de 50 productos.

In [30]:
UMBRAL_CATEGORIA = 50
conteo = df["categoria"].value_counts()
categorias_chicas = conteo[conteo < UMBRAL_CATEGORIA].index.tolist()
df = df[~df["categoria"].isin(categorias_chicas)].reset_index(drop=True)
log("7. Eliminar categorías pequeñas",
    f"Descartadas por extracción incompleta (<{UMBRAL_CATEGORIA} productos): {categorias_chicas}")

[7. Eliminar categorías pequeñas] Descartadas por extracción incompleta (<50 productos): ['Limpieza']  |  filas: 1504 -> 1491 (-13)

### Paso 8 — Variables derivadas

Se recalcula `descuento_pct` desde los precios ya validados (no se confía en el valor que
traía el crudo) y se agregan variables de análisis:

- **`descuento_pct`** = `(1 − precio_venta / precio_regular) × 100`, 0 si no hay oferta.
- **`tiene_descuento`** (bool) = hay oferta activa.
- **`ahorro_soles`** = `precio_regular − precio_venta`.
- **`fecha_extraccion`** convertida a `datetime`.

In [31]:
hay_oferta = df["precio_regular"] > df["precio_venta"]
df["descuento_pct"] = 0.0
df.loc[hay_oferta, "descuento_pct"] = (
    (1 - df["precio_venta"] / df["precio_regular"]) * 100
).round(2)
df["tiene_descuento"] = hay_oferta
df["ahorro_soles"] = (df["precio_regular"] - df["precio_venta"]).round(2)
df["fecha_extraccion"] = pd.to_datetime(df["fecha_extraccion"], errors="coerce")

log("8. Variables derivadas",
    "descuento_pct recalculado; + tiene_descuento, ahorro_soles; fecha a datetime")

[8. Variables derivadas] descuento_pct recalculado; + tiene_descuento, ahorro_soles; fecha a datetime  |  filas: 1491 -> 1491 (+0)

## 14. Bitácora de limpieza

Registro completo de las decisiones. Es la evidencia que defiende el criterio *Calidad de los
datos* ante el docente: cada transformación con su justificación y su impacto en el número de
filas.

In [32]:
df_bitacora = pd.DataFrame(bitacora)
df_bitacora

,paso,decision,filas_antes,filas_despues,delta
0,1. Normalización de texto,Espacios colapsados; marca a mayúsculas; categ...,1504,1504,0
1,2. Renombrar sku -> id_producto,La columna no es un SKU sino el slug de la URL...,1504,1504,0
2,3. Deduplicar por url_producto,Duplicados por identificador único real; nunca...,1504,1504,0
3,4. Eliminar columna url_imagen,1341 valores (15.5%) apuntaban al octógono nut...,1504,1504,0
4,5. Tipado de precios,precio_venta y precio_regular a numérico; valo...,1504,1504,0
5,6. Coherencia de precios,precio_regular < precio_venta igualado al de v...,1504,1504,0
6,7. Eliminar categorías pequeñas,Descartadas por extracción incompleta (<50 pro...,1504,1491,-13
7,8. Variables derivadas,"descuento_pct recalculado; + tiene_descuento, ...",1491,1491,0

## 15. Verificación de la rúbrica

Tabla de nulos antes/después y comprobación explícita de los cuatro requisitos duros,
impresa como booleanos.

In [33]:
comp_nulos = pd.DataFrame({
    "nulos_%_crudo": (df_crudo.isnull().mean() * 100).round(2),
}).join(
    pd.DataFrame({"nulos_%_limpio": (df.isnull().mean() * 100).round(2)}),
    how="outer",
)
print("Nulos por columna, antes vs después (columnas eliminadas quedan como NaN):")
comp_nulos

Nulos por columna, antes vs después (columnas eliminadas quedan como NaN):

                  nulos_%_crudo  nulos_%_limpio
ahorro_soles                NaN             0.0
categoria                  0.00             0.0
descuento_pct              0.00             0.0
fecha_extraccion           0.00             0.0
id_producto                 NaN             0.0
marca                      0.00             0.0
nombre                     0.00             0.0
precio_regular             0.00             0.0
precio_venta               0.00             0.0
sku                        0.00             NaN
tiene_descuento             NaN             0.0
tiene_precio_oh            0.00             0.0
url_imagen                72.94             NaN
url_producto               0.00             0.0

In [34]:
max_nulos = (df.isnull().mean() * 100).max()
dups = int(df["url_producto"].duplicated().sum())

checks = {
    "> 1000 registros":            len(df) > 1000,
    ">= 6 atributos":              df.shape[1] >= 6,
    "<= 10% nulos por columna":    max_nulos <= 10,
    "sin duplicados (url_producto)": dups == 0,
}

print(f"registros           : {len(df)}")
print(f"atributos           : {df.shape[1]}")
print(f"máx. % nulos columna: {max_nulos:.2f}")
print(f"duplicados url      : {dups}")
print("-" * 40)
for req, ok in checks.items():
    print(f"{'OK ' if ok else 'FALLA'}  {req}: {ok}")
print("-" * 40)
print("TODOS LOS REQUISITOS:", all(checks.values()))

registros           : 1491
atributos           : 12
máx. % nulos columna: 0.00
duplicados url      : 0
----------------------------------------
OK   > 1000 registros: True
OK   >= 6 atributos: True
OK   <= 10% nulos por columna: True
OK   sin duplicados (url_producto): True
----------------------------------------
TODOS LOS REQUISITOS: True

## 16. Perfil del dataset limpio

Retrato del resultado: distribución por categoría, diversidad de marcas, rango de precios y
comportamiento de los descuentos.

In [35]:
print("productos por categoría:")
print(df["categoria"].value_counts(), "\n")
print("marcas distintas :", df["marca"].nunique())
print("rango de precios : S/ {:.2f} - S/ {:.2f}".format(
    df["precio_venta"].min(), df["precio_venta"].max()))
print("productos con descuento: {} ({:.1f} %)".format(
    int(df["tiene_descuento"].sum()), df["tiene_descuento"].mean() * 100))

productos por categoría:
categoria
Abarrotes            150
Bebidas              150
Lácteos              150
Cuidado Personal     150
Frutas y Verduras    150
Carnes y Pescados    150
Desayunos            150
Quesos y Fiambres    149
Panadería            147
Congelados           145
Name: count, dtype: int64

marcas distintas : 279
rango de precios : S/ 0.90 - S/ 999.00
productos con descuento: 383 (25.7 %)

In [36]:
print("descuento promedio y ahorro promedio por categoría (solo con oferta):")
con_oferta = df[df["tiene_descuento"]]
resumen = con_oferta.groupby("categoria").agg(
    productos_con_oferta=("descuento_pct", "size"),
    descuento_pct_prom=("descuento_pct", "mean"),
    ahorro_soles_prom=("ahorro_soles", "mean"),
).round(2).sort_values("descuento_pct_prom", ascending=False)
resumen

descuento promedio y ahorro promedio por categoría (solo con oferta):

                   productos_con_oferta  descuento_pct_prom  ahorro_soles_prom
categoria
Cuidado Personal                     99               30.88              90.81
Quesos y Fiambres                    34               17.66               2.34
Congelados                           22               17.47               3.50
Desayunos                            46               17.32               3.83
Abarrotes                            47               16.58               2.04
Frutas y Verduras                    13               15.50               1.10
Panadería                            30               13.72               1.15
Lácteos                              26               13.23               1.91
Carnes y Pescados                    18               10.70               2.57
Bebidas                              48               10.69               1.19

## 17. Limitaciones del dataset

Estas limitaciones nacen de cómo se extrajeron los datos (secciones 1–10) y acotan qué
análisis son válidos. Declararlas es parte del control de calidad y del *Alcance* del informe.

- **Muestreo por tope.** La extracción usó `max_productos = 150` por categoría, así que el
  dataset no es el catálogo completo sino los primeros ~150 productos que el sitio muestra en
  cada categoría, en el orden por defecto. **No es una muestra aleatoria**, por lo que no debe
  extrapolarse al catálogo entero de plazaVea.
- **Foto de un momento.** Los precios son del **16/09/2026**. plazaVea cambia promociones con
  frecuencia; el dataset es un corte transversal y **no permite análisis temporal**.
- **Dependencia de la zona de entrega.** El catálogo y los precios de plazaVea varían según la
  ubicación configurada en el sitio. Los datos corresponden a la **zona por defecto, sin sesión
  iniciada**.
- **Categoría `Limpieza` excluida** por extracción incompleta (15 de ~150 productos). Las
  conclusiones no cubren esa categoría.
- **Sin columna de imagen.** Se eliminó `url_imagen` por no ser confiable (15.5 % apuntaba al
  octógono nutricional). El dataset no soporta análisis que dependa de la foto del producto.

## 18. Exportación y columnas finales

Se exporta a `data/processed/plazavea_limpio.csv` en UTF-8. **Las 12 columnas de abajo quedan
congeladas**: el diccionario de datos parte de esta lista.

In [37]:
OUT.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(OUT, index=False, encoding="utf-8")

print("exportado a:", OUT)
print("forma final:", df.shape)
print("\ncolumnas finales congeladas para el diccionario de datos:")
for i, (col, tipo) in enumerate(df.dtypes.items(), 1):
    print(f"  {i:2d}. {col:<18} {tipo}")

exportado a: ..\data\processed\plazavea_limpio.csv
forma final: (1491, 12)

columnas finales congeladas para el diccionario de datos:
   1. id_producto        object
   2. nombre             object
   3. marca              object
   4. categoria          object
   5. precio_venta       float64
   6. precio_regular     float64
   7. tiene_precio_oh    bool
   8. descuento_pct      float64
   9. url_producto       object
  10. fecha_extraccion   datetime64[ns]
  11. tiene_descuento    bool
  12. ahorro_soles       float64